# Generated by Django 5.1.6 on 2025-02-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='category',
            new_name='question_category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='optionA',
        ),
        migrations.RemoveField(
            model_name='question',
            name='optionB',
        ),
        migrations.RemoveField(
            model_name='question',
            name='optionC',
        ),
        migrations.RemoveField(
            model_name='question',
            name='optionD',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='incorrect_answers',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
