# Generated by Django 5.1.5 on 2025-02-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_scoreboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='userName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
