# Generated by Django 5.1.5 on 2025-02-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_scoreboard_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='question_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='score',
            field=models.BigIntegerField(default=0),
        ),
    ]
