# Generated by Django 5.1.5 on 2025-02-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_scoreboard_question_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='question_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
